#!/usr/bin/env node

const fs = require("fs");

if (!fs.existsSync(".devcontainer/devcontainer.json")) {
  fs.mkdirSync(".devcontainer", { recursive: true });
  fs.writeFileSync(
    ".devcontainer/devcontainer.json",
    JSON.stringify(
      {
        name: "FSH in VS Code",
        image: "ghcr.io/bonfhir/ig-toolbox:latest",
        remoteUser: "root",
        customizations: {
          vscode: {
            extensions: ["MITRE-Health.vscode-language-fsh", "jebbs.plantuml"],
          },
        },
      },
      undefined,
      2
    )
  );
}

if (!fs.existsSync(".vscode/tasks.json")) {
  fs.mkdirSync(".vscode", { recursive: true });
  fs.writeFileSync(
    ".vscode/tasks.json",
    JSON.stringify(
      {
        version: "2.0.0",
        tasks: [
          {
            label: "Run SUSHI",
            type: "shell",
            command: "sushi .",
            group: {
              kind: "build",
              isDefault: true,
            },
            presentation: {
              reveal: "always",
              focus: false,
              panel: "shared",
              clear: false,
            },
            problemMatcher: [],
          },
          {
            label: "Update IG Publisher",
            type: "shell",
            command: "./_updatePublisher.sh -y",
            presentation: {
              reveal: "always",
              focus: false,
              panel: "shared",
              showReuseMessage: false,
              clear: false,
            },
            problemMatcher: [],
          },
          {
            label: "Run IG Publisher",
            type: "shell",
            command: "./_genonce.sh",
            group: {
              kind: "build",
            },
            presentation: {
              reveal: "always",
              focus: false,
              panel: "shared",
              clear: false,
            },
            problemMatcher: [],
          },
          {
            label: "Add new profile",
            type: "shell",
            command: "add-profile ${input:name}",
            options: {
              cwd: "${workspaceFolder}",
            },
            presentation: {
              echo: false,
              reveal: "silent",
              focus: false,
              panel: "shared",
              showReuseMessage: false,
              clear: false,
            },
            problemMatcher: [],
          },
          {
            label: "Add new diagram",
            type: "shell",
            command: "add-fhir-resource-diagram ${input:name}",
            options: {
              cwd: "${workspaceFolder}",
            },
            presentation: {
              echo: false,
              reveal: "always",
              focus: false,
              panel: "shared",
              showReuseMessage: false,
              clear: false,
            },
            problemMatcher: [],
          },
        ],
        inputs: [
          {
            id: "name",
            description: "Name",
            default: "",
            type: "promptString",
          },
        ],
      },
      undefined,
      2
    )
  );
}
