#!/usr/bin/env node

const fs = require("fs");

let profile = process.argv[2];

if (!profile?.length > 2) {
  console.error("Usage: add-profile <profile-name>");
  process.exit(1);
}

profile = profile[0].toUpperCase() + profile.slice(1);

if(fs.existsSync(`input/fsh/profiles/${profile}.fsh`)) {
  console.error(`File input/fsh/profiles/${profile}.fsh already exists. Skipping.`);
  process.exit(1);
}

fs.writeFileSync(`input/fsh/profiles/${profile}.fsh`, `Profile: ${profile}`);
fs.writeFileSync(`input/pagecontent/StructureDefinition-${profile}-intro.md`, ``);