#!/usr/bin/env node

const fs = require("fs");

if (!fs.existsSync(".devcontainer/devcontainer.json")) {
  fs.mkdirSync(".devcontainer", { recursive: true });
  fs.writeFileSync(
    ".devcontainer/devcontainer.json",
    JSON.stringify(
      {
        "name": "FSH in VS Code",
        "image": "ig-toolbox:latest",
        "workspaceMount": "source=${localWorkspaceFolder},target=/workspaces,type=bind",
        "workspaceFolder": "/workspaces",
        "forwardPorts": [
          80
        ],
        "customizations": {
          "vscode": {
            "settings": {
              "terminal.integrated.defaultProfile.linux": "bash",
              "yaml.schemas": {
                "https://json.schemastore.org/github-workflow.json": "/.github/workflows/*",
                "https://raw.githubusercontent.com/HL7/fhir-ig-publisher/master/org.hl7.fhir.publisher.schema.json": "ig.ini"
              }
            },
            "extensions": [
              "MITRE-Health.vscode-language-fsh",
              "jebbs.plantuml",
              "redhat.vscode-yaml",
              "esbenp.prettier-vscode",
              "ms-azuretools.vscode-docker",
              "ms-vscode-remote.remote-containers"
            ]
          }
        }
      },
      undefined,
      2
    )
  );
}

if (!fs.existsSync(".vscode/tasks.json")) {
  fs.mkdirSync(".vscode", { recursive: true });
  fs.writeFileSync(
    ".vscode/tasks.json",
    JSON.stringify(
      {
        version: "2.0.0",
        tasks: [
          {
            label: "Run SUSHI",
            type: "shell",
            command: "sushi .",
            group: {
              kind: "build",
              isDefault: true,
            },
            presentation: {
              reveal: "always",
              focus: false,
              panel: "shared",
              clear: false,
            },
            problemMatcher: [],
          },
          {
            label: "Update IG Publisher",
            type: "shell",
            command: "./_updatePublisher.sh -y",
            presentation: {
              reveal: "always",
              focus: false,
              panel: "shared",
              showReuseMessage: false,
              clear: false,
            },
            problemMatcher: [],
          },
          {
            label: "Run IG Publisher",
            type: "shell",
            command: "./_genonce.sh",
            group: {
              kind: "build",
            },
            presentation: {
              reveal: "always",
              focus: false,
              panel: "shared",
              clear: false,
            },
            problemMatcher: [],
          },
          {
            label: "Add new profile",
            type: "shell",
            command: "add-profile.js",
            args: ["${file}", "${input:name}"],
            presentation: {
              echo: false,
              reveal: "silent",
              focus: false,
              panel: "shared",
              showReuseMessage: false,
              clear: false,
            },
            problemMatcher: [],
          },
          {
            label: "Add new diagram",
            type: "shell",
            command: "add-fhir-resource-diagram ${input:name}",
            options: {
              cwd: "${workspaceFolder}",
            },
            presentation: {
              echo: false,
              reveal: "always",
              focus: false,
              panel: "shared",
              showReuseMessage: false,
              clear: false,
            },
            problemMatcher: [],
          },
        ],
        inputs: [
          {
            id: "name",
            description: "Name",
            default: "",
            type: "promptString",
          },
        ],
      },
      undefined,
      2
    )
  );
}
